Added SwiftLint as pod dependency
rootstrap/ios-base pull request #185
Opened 2021-08-18 19:14 UTC by LeandroHiga

#### Description:

* Add SwiftLint as pod dependency

---
#### Tasks:

* [ISSUE-176](https://github.com/rootstrap/ios-base/issues/176)

2021-08-18 19:16 UTC, pMalvasio commented on Podfile
> +  pod 'SwiftLint'
Follow the same notation and after running the `pod install` command, specify the current version `, '~> x.x.x'`

2021-08-18 19:28 UTC, pMalvasio commented on Podfile.lock
> +COCOAPODS: 1.11.0.beta.1
Watch out with the `cocoapod` version 🙈 I'd recommend `1.11` to keep things stable. Maybe anyone else have another opinion about the version 🤔

2021-08-18 20:15 UTC, pMalvasio approved these changes

2021-08-18 20:27 UTC, germanStabile approved these changes

2021-08-20 15:53 UTC, CamilaMoscatelli approved these changes

2021-08-20 16:33 UTC, glm4 requested changes

2021-08-20 16:33 UTC, glm4 commented on ios-base.xcodeproj/project.pbxproj
> +			shellScript = "if which \"${PODS_ROOT}/SwiftLint/swiftlint\" >/dev/null; then\n${PODS_ROOT}/SwiftLint/swiftlint\nelse\necho \"warning: SwiftLint not installed, download from https://github.com/rea
The entire script should be replaced by:
"${PODS_ROOT}/SwiftLint/swiftlint"

2021-08-20 16:33 UTC, glm4 commented on ios-base.xcodeproj/project.pbxproj
> +			shellScript = "if which \"${PODS_ROOT}/SwiftLint/swiftlint\" >/dev/null; then\n${PODS_ROOT}/SwiftLint/swiftlint\nelse\necho \"warning: SwiftLint not installed, download from https://github.com/rea
@LeandroHiga ☝️

2021-08-20 17:06 UTC, glm4 approved these changes

2021-08-23 12:23 UTC, merged